Refactor
Teaching-projects/-SZE-MOSZE-2020-AMD_Bike pull request #12
Opened 2020-11-05 23:11 UTC by hajdunorbi

@hegyhati Sikerült elkészíteni a refactor-t végre. 😄 Reméljük még nem túl késő és van időd ránézni

2020-11-06 13:03 UTC, hegyhati requested changes
A jelzett mellett globalisan idegesito, hogy scenario-nak neveztetek el minden letezo map-et, amit beparse-oltok, holott egyerdul a scenario.json-ok esetbeen scenario ez. Szoval annak a nevet mindenkepp csereljetek le valami ertelmesebbre. De ezt leszamitva jonak tunik.

2020-11-06 13:03 UTC, hegyhati commented on .github/workflows/Doxygen.yml
> +      - refactor
nana, az maradjon csak szepen master.

2020-11-06 19:04 UTC, Szabi1104 commented on .github/workflows/Doxygen.yml
> +      - refactor
Rendben, visszaírtuk! :)

2020-11-06 19:08 UTC, Szabi1104 commented
@hegyhati Átírtuk vissza a yml fájlban a refactort masterre és a scenario változóneveket mindenhol lecseréltük. Reméljük így akkor rendben van a kód! 😄

2020-11-08 12:57 UTC, hegyhati approved these changes

2020-11-08 12:57 UTC, merged