Game
Teaching-projects/-SZE-MOSZE-2020-AMD_Bike pull request #20
Opened 2020-11-30 13:43 UTC by Szabi1104

Elkészültünk a Game feladattal is, srácok légyszi ha lesz időtök majd lessetek rá, köszi! 😉

2020-12-03 20:12 UTC, balazs482 approved these changes
A main túl robosztus, hogy így első olvasatra átlássam, de gondolom mindent jól használ a game-ből, szóval minden szuper.

2020-12-08 10:16 UTC, gboldi19 requested changes
Azt az egy kommentet leszámítva megfelelő lesz. A menü nagyon jó lett! :D

2020-12-08 10:16 UTC, gboldi19 commented on Monster.cpp
> +	}*/
Amennyiben ezt nem használjátok, kérlek töröljétek!

2020-12-08 16:41 UTC, skrobi12 commented on Monster.cpp
> +	}*/
foggalmam sincs, hogy hogyan kerül ez mindig vissza :D

2020-12-08 16:41 UTC, hajdunorbi approved these changes

2020-12-08 16:41 UTC, merged