Markedmap
Teaching-projects/-SZE-MOSZE-2020-AMD_Bike pull request #21
Opened 2020-11-30 14:31 UTC by Szabi1104

Elkészült a MarkedMap feladat is, légyszi majd nézzetek rá srácok ha időtök engedi!

2020-12-03 20:14 UTC, balazs482 approved these changes
Működik meg minden, szóval részemről tökéletes.

2020-12-08 10:21 UTC, gboldi19 requested changes
Ezt az egy észrevételt leszámítva jó!

2020-12-08 10:21 UTC, gboldi19 commented on Monster.cpp
> +	}*/
Szintén, ha kérhetem törölni

2020-12-08 16:39 UTC, skrobi12 commented on Monster.cpp
> +	}*/
Máig nem értem ez hogy kerül mindig vissza, amikor töröljük :D

2020-12-08 16:41 UTC, skrobi12 approved these changes

2020-12-08 16:42 UTC, merged

2020-12-08 16:43 UTC, skrobi12 commented on Monster.cpp
> +	}*/
A végén biztos ez lesz az a dolog amit megnézek, hogy bent maradt-e vagy sem...