Development2
Teaching-projects/-SZE-MOSZE-2020-AMD_Bike pull request #3
Opened 2020-09-24 20:59 UTC by skrobi12

@hegyhati Bár az első feladat még nincs merge-ölve, a hibákat amiket mondtál kijavítottuk. Viszont a határidőre való tekintettel szeretnénk a 2 feladatra is leadni a kódunkat.

2020-09-26 13:28 UTC, hegyhati commented
Rebase-eljetek a masterre, aztan utana nezunk ra.

2020-09-27 22:58 UTC, skrobi12 commented
@hegyhati Megtörtént a rebase! Remélem nem rontottam el semmit, ahogy azt a merge-el tettem... D:

2020-10-01 11:58 UTC, skrobi12 commented
@hegyhati Hello, ahogy kérted újra tag-elünk!

2020-10-01 16:38 UTC, hegyhati requested changes

2020-10-01 16:38 UTC, hegyhati commented on .github/workflows/Test.yml
> +      - run: chmod +x test.sh
ezeket nem tul szep itt, miert nem csinaljatok meg egyszer lokalisan?

2020-10-01 16:38 UTC, hegyhati commented on Character.cpp
> +	if (file.is_open()) {
es mi van, ha nem sikerult?

2020-10-01 16:38 UTC, hegyhati commented on Character.cpp
> +	file.close();
akkor is lezarod, ha nem sikerult megnyitni?

2020-10-01 16:38 UTC, hegyhati commented on Character.cpp
> +	return character;
ez megy szerintem egy sorban is.

2020-10-01 16:38 UTC, hegyhati commented on Character.h
> +	static Character parseUnit(const std::string FileName);
feleslegesen ne masoljuk a fajlnevet.

2020-10-01 16:38 UTC, hegyhati commented on main.cpp
> +	else { file1.close(); file2.close(); return false; }
ez kicsit overkill azert, meg foleg ket parameterrel. Ha csinaltok ilyet, akkor eggyel. ha nem sikerult megnyitni, akkor itt sem kell close-olni.

2020-10-01 16:38 UTC, hegyhati commented on main.cpp
> +		return 1;
szoval egyreszt akkor baromira felrevezeto a nev, masreszt az volt a feladat, hogy exceptiont dobjon.

2020-10-01 16:38 UTC, hegyhati commented on test.sh
> +./a.out units/Vader.json units/Luke.json >> output.txt
nem art az elejen torolni az output-ot

2020-10-01 16:38 UTC, hegyhati commented on test.sh
> +fi
Namost ezzel el is szurtatok, ez a shell script sosem fog nem 0-t visszadobni...

2020-10-01 22:02 UTC, skrobi12 commented
@hegyhati Ha minden igaz, minden javasolt dolog megoldásra került! Volt amit teljes egészében átirtunk, mert úgy láttuk észszerűnek. Ha még van benne hiba, akkor tudasd velünk :)

2020-10-06 14:18 UTC, skrobi12 commented
@hegyhati  itt vagyunk! Eltelt több mint 3 nap, és még mindig nem jött válasz :(

2020-10-06 14:27 UTC, hegyhati requested changes
Igazabol ket olyan hiba van, ami korabban is mar meg lett irva...

2020-10-06 14:27 UTC, hegyhati commented on Character.cpp
> +	file.close();
meg mindig aktualis

2020-10-06 14:27 UTC, hegyhati commented on test.sh
> +fi
ez mikor ter vissza nem 0-val? ugyanaz a problema mint korabban

2020-10-06 14:27 UTC, skrobi12 commented
Akkor ezeket megnézzük!

2020-10-06 15:33 UTC, hajdunorbi commented
@hegyhati Reméljük most már tényleg készen áll a merge-re :)

2020-10-06 23:01 UTC, hegyhati approved these changes

2020-10-06 23:02 UTC, merged