Jsonparser
Teaching-projects/-SZE-MOSZE-2020-AMD_Bike pull request #6
Opened 2020-10-14 17:20 UTC by skrobi12

@wajzy Jó estét kívánok Tanár Úr! Ha minden igaz sikerült lefuttatnom a jsonparserem! Valószínüleg nem hibátlan, úgyhogyha a Tanár Úrnak bármilyen észrevétele van, akkor azt meg is próbálom rögtön kijavítani!

2020-10-18 14:03 UTC, wajzy requested changes
Légy szíves, készítsd fel a kódot néhány könnyen elkövethető hiba detektálására, majd ezt a képességét teszteld is! Kérek még egy harmadik tagfüggvényt a parzerbe, hogy a funkciók világosan elkülönüljenek.

2020-10-18 14:03 UTC, wajzy commented on Character.cpp
> +	else { return false; }
Így is jól működik, csak hosszabb a kód, mint eddig. Nem értem, mi indokolta a változtatást.

2020-10-18 14:03 UTC, wajzy commented on JsonParser.cpp
> +			}
Kérlek ellenőrizd, hogy nem olvassa-e be az utolsó sort kétszer!

2020-10-18 14:03 UTC, wajzy commented on JsonParser.cpp
> +std::map<std::string, std::string> JsonParser::Parser(std::string Data)
Legyen két külön fv. a string parzolására és a fájlnévvel adott fájl tartalmának feldolgozására, ne keverd őket egy függvényben!

2020-10-18 14:03 UTC, wajzy commented on JsonParser.cpp
> +		}
És mi fog történni, ha egyetlen további idézőjel sincs a json fájlban? Fel kellene készíteni a rutint legalább néhány, elgépelésből eredő hiba felderítésére, kezelésére!

2020-10-18 14:03 UTC, wajzy commented on JsonParser.h
> +	static std::map<std::string, std::string> Parser(std::istream& Istream);
Ide kellene még egy harmadik fv. Ha kell, nevezd át őket!

2020-10-18 14:03 UTC, wajzy commented on test/UnitTest.cpp
> +}
OK, de legyen olyan teszteset is, ami hibás/hiányos fájlok parzolását ellenőrzi!

2020-10-19 19:22 UTC, skrobi12 commented
@wajzy Ha minden igaz sikerült a Tanár Úr minden észrevételét kijavítanom! Ha esetleg vannak további hibák, akkor természetesen javítom őket!

2020-10-24 13:11 UTC, wajzy requested changes
Még mindig hiányérzetem van.

2020-10-24 13:11 UTC, wajzy commented on JsonParser.cpp
> +}
Ez a függvény továbbra is vagy a string tartalmát ellenőrzi, vagy fájlnévnek tekinti azt. Azt kértem, hogy válaszd szét ezt a két feladatot két függvénybe. (Bár nem valószínű, hogy a json fájl tartalma .json-ra végződjön, tisztább lenne a helyzet.)

2020-10-24 13:11 UTC, wajzy commented on test/units/WrongLuke.json
> +}
Akármilyen erősen nézem, én ebben nem látok formai hibát.

2020-10-24 13:11 UTC, wajzy commented on test/UnitTest.cpp
> +}
Ez nem azt teszteli, hogy a parzer elboldogul-e egy hibás fájl feldolgozásával. Hozz létre olyan tesztesetet, amiben pl. elfelejtik lezárni az idézőjeles részt, kifelejtik a vesszőt, kettőspontot, stb.

2020-10-25 20:27 UTC, skrobi12 commented
@wajzy Csináltam egy ténylegesen hibásan megadott "WrongUnit" tesztet, ahol a unit-nak kitöröltem a "hp" sorát, és így írtam rá egy ASSERT_THROW-t, valamint ha jól értelmeztem akkor a kért függvényt is átírtam, viszont ebben nem vagyok biztos, hogy erre gondolt a Tanár Úr. :)

2020-10-28 08:13 UTC, wajzy commented
Alakul. Készíts olyan tesztesetet, ami HIBÁS és nem csak HIÁNYOS fájlt ellenőriz. Ahogyan korábban is írtam már: "Hozz létre olyan tesztesetet, amiben pl. elfelejtik lezárni az idézőjeles részt, kifelejtik a vesszőt, kettőspontot, stb."

2020-10-28 13:56 UTC, skrobi12 commented
@wajzy Most már van olyan teszteset is, ami hibás adatot vár, ami azt vizsgálja, hogy hp, illetve dmg adatoknál valóban szám adatok vannak-e megadva. Remélem így már ténylegesen kész a kód! :)

2020-10-31 10:07 UTC, wajzy approved these changes
OK, menjen az ütközések feloldása.

2020-10-31 15:13 UTC, skrobi12 commented
@wajzy Ha minden igaz minden conflict fel lett oldva!

2020-11-02 13:12 UTC, skrobi12 commented
@wajzy készen áll a merge!

2020-11-04 15:57 UTC, hegyhati commented
Sracok, beviszem ezt. A masik kettot brutalgyorsan vigyetek be, a refactorra ket napotok van.

2020-11-04 15:57 UTC, merged

2020-11-04 15:59 UTC, skrobi12 commented
Épp órán ülünk, de akkor gyors felviszem azt a kettőt! A refactor igazából már kész van lokálisan, akkor azt csak fel kell pusholni! Nagyon szépen köszönjük szépen a merge-et :D